### ISSUE TITLE
undefined reference to `vtable for st7567sfGKAdafruit'

### ISSUE THREAD

**Issue by Beerlesklopfer** [holgerlembke/st7567sfGK#1]
Maybe you want to add 

st7567sfGK.h: 
```
   public:  //---------
    st7567sfGKAdafruit() { tfofs = 0; }
    virtual ~st7567sfGKAdafruit();
```

st7567sfGK.cpp: 

```
st7567sfGKAdafruit::~st7567sfGKAdafruit() {    
}
```

and also to the st7567sfGK class.  It is too short fo a pull request... Thanks...

**Comment by holgerlembke** [comment]
I see your point but I don't get this message. Which platform throws it?

**Comment by Beerlesklopfer** [comment]
[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink

**Comment by holgerlembke** [comment]
OK, I can reproduce the problem.

Is that a valid compiler behavior? I mean, the default destructor should be created automatically? Shouldn't it?

Why does 
```
virtual ~st7567sfGKAdafruit() = default;
``` 
not work?

That is very confusing.

**Comment by Beerlesklopfer** [comment]
[This helped me to solve the problem](https://stackoverflow.com/questions/3065154/undefined-reference-to-vtable)

**Comment by holgerlembke** [comment]
Ok, looks like the confusion has been resolved.

As I assumed the missing destructor was a misleading error message.  The real problem was my inline attribute at [inline size_t st7567sfGKAdafruit::write(uint8_t value) ](https://github.com/holgerlembke/st7567sfGK/blob/8ae96789f7bd974a6f40a42a90417e1f95811f69/src/st7567sfGK.cpp#L638). Inlining a virtual function is not a smart idea[1]. OTOH the compiler happily eats that code without complain...

After removing the inline from both write functions the code compiles fine for bluepill_f103c8.

Thanks goes to Andreas Frisch for showing the error.

1: Afterthought: Well, if an object is created by "classname objectname;" then the compiler knows where the virtual function call goes. It could even generate code to avoid the virtual table lookup code. Only if we have a pointer like in "classname * objectname" the compiler does not really know where the function will point to. (Just ignoring the edge case of "classname * objectname = new classname();".) I still like the idea that the compiler should throw warnings... But what does /me minor mortal earthling know.
